# Generated by Django 2.1.3 on 2019-01-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Libro id')),
                ('titulo', models.CharField(max_length=80)),
                ('autor', models.CharField(max_length=80)),
                ('año_publicacion', models.IntegerField(verbose_name='Año publicacion')),
                ('editor', models.CharField(max_length=80)),
                ('urls', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(verbose_name='Puntuacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Usuario id')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('localizacion', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='isUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaRecomendacion_app.Usuario'),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaRecomendacion_app.Libro'),
        ),
    ]
