# Generated by Django 2.1.3 on 2019-01-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaRecomendacion_app', '0002_auto_20190109_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntuacion',
            old_name='isUsuario',
            new_name='idUsuario',
        ),
    ]
