# Generated by Django 2.1.3 on 2019-01-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaRecomendacion_app', '0003_auto_20190109_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntuacion',
            old_name='isbn',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='puntuacion',
            old_name='idUsuario',
            new_name='usuario',
        ),
    ]
